[package]
name = "epyxid"
version = "0.3.6"
edition = "2021"
description = "Python wrapper around Rust implementation of XID (Globally Unique ID Generator)"
license = "MIT"
repository = "https://github.com/shpaker/epyxid"
homepage = "https://github.com/shpaker/epyxid"
authors = ["Aleksandr Shpak <shpaker@gmail.com>"]
keywords = ["xid", "pyo3"]
exclude = [
    "target/",
    "venv/",
    ".github/",
    "*.pyc",
    "__pycache__/",
    ".gitignore",
    "prek.toml",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "epyxid"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.2", features = ["abi3-py38"] }
xid = "1.1.1"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true
