from datetime import datetime
from typing import Tuple


class XID:

    @staticmethod
    def create() -> 'XID': ...

    @staticmethod
    def from_str(s: str) -> 'XID': ...

    def as_bytes(self) -> bytes: ...

    def as_str(self) -> str: ...

    def machine(self) -> Tuple[int, int, int]: ...

    def pid(self) -> int: ...

    def time(self) -> datetime: ...

    def counter(self) -> int: ...
