name: TESTS

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - run: |
          python -m pip install poetry~=1.8.2
          poetry install --no-root --no-ansi --with ${{ matrix.JUST_JOB }}
      - run: just ${{ matrix.JUST_JOB }}
