name: TESTS

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - run: |
          python -m pip install pytest~="8.0.2"
          maturin develop
      - run:
          pytest -v test_xid.py
