name: TESTS

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - run: |
          python -m pip install poetry~=1.8.2
          poetry install --no-root --no-ansi --with tests
          poetry run maturin develop
      - run:
          poetry run pytest -v test_xid.py
